# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-12 00:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_central', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetaSubscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_updated_at', models.DateTimeField(auto_now=True)),
                ('db_created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('ip', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'beta_subscriber',
            },
        ),
    ]
