# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-01-05 05:33
from __future__ import unicode_literals

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app_central', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='burrito',
            name='banner_color_scheme',
            field=jsonfield.fields.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burrito',
            name='banner_message',
            field=models.TextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='burrito',
            name='banner_url',
            field=models.TextField(null=True),
        ),
    ]
